language: java
jdk: openjdk10

sudo: required

services:
- docker

before_install:
- echo $PWD
- wget http://central.maven.org/maven2/com/codacy/codacy-coverage-reporter/5.0.310/codacy-coverage-reporter-5.0.310-assembly.jar
#- docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

after_success:
- java -jar ./codacy-coverage-reporter-5.0.310-assembly.jar report -l Java -r ./target/site/jacoco-ut/jacoco.xml
#docker commands follow now
- docker build -t $DOCKER_USERNAME/backend-image .
- docker tag $DOCKER_USERNAME/backend-image registry.heroku.com/$HEROKU_APP_NAME/web
- docker images

before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #docker credentials are set in travis enviroment variables

deploy:
  provider: script
  script: docker push myorg/myimage

#deploy:
#  provider: heroku
#  api_key:
#    secure: $HEROKU_API_KEY
#  app: $HEROKU_APP_NAME
#  on:
#    repo: $DOCKER_USERNAME/backend-image


#deploy:
#  provider: script
#  script:
#     docker tag backend-image $DOCKER_USERNAME/backend-image;
#   docker push registry.heroku.com/$HEROKU_APP_NAME/web;
