language: java
jdk: openjdk10

sudo: required

services:
 - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
- echo $PWD
- wget http://central.maven.org/maven2/com/codacy/codacy-coverage-reporter/5.0.310/codacy-coverage-reporter-5.0.310-assembly.jar
- wget -qO- https://toolbelt.heroku.com/install.sh | sh #install heroku CLI

after_success:
- java -jar ./codacy-coverage-reporter-5.0.310-assembly.jar report -l Java -r ./target/site/jacoco-ut/jacoco.xml
#docker commands follow now
- docker build -t "$DOCKER_USERNAME"/backend-image:$COMMIT .
- docker tag "$DOCKER_USERNAME"/backend-image:$COMMIT registry.heroku.com/"$HEROKU_APP_NAME"/web
- docker images

before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #docker credentials are set in travis enviroment variables
- heroku login
- heroku container:login
- heroku container:push web
- heroku container:release web

deploy:
- provider: script
  script: bash scripts/deploy-script.sh

#  - provider: heroku
#    api_key:
#      secure: $HEROKU_API_KEY
#    app: $HEROKU_APP_NAME
#    on:
#      repo: $DOCKER_USERNAME/backend-image:$COMMIT